# Generated by Django 4.2.3 on 2023-08-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_pictuer'),
        ('store', '0005_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
