# Generated by Django 4.2.3 on 2023-08-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_reviewrating_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
